apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt-vm: vm-{{.name}}-{{.Replica}}
  name: {{.name}}-{{.Replica}}
spec:
  preference:
    name: windows.2k25.virtio
  ## controls if the VM boots up on creation:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt-vm: vm-{{.name}}-{{.Replica}}
        kubevirt.io/os: {{.OS}}
    spec:
      domain:
        ## vcpus:
        cpu:
          cores: {{.cpuCores}}
          sockets: 1
       ## create 2 VM disks (rootdisk clone, cloudinit)
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          ## default network interface:
          interfaces:
          - masquerade: {}
            model: virtio
            name: default
          networkInterfaceMultiqueue: true
          rng: {}
        ## VM memory size:
        memory:
          guest: {{.memory}}
      ## default pod network:
      networks:
      - name: default
        pod: {}
      ## volume definitions for the VM disks:
      volumes:
      - dataVolume:
          name: dvclone-{{.Replica}}
        name: rootdisk
  dataVolumeTemplates:
  ## rootdisk:
  - metadata:
      name: dvclone-{{.Replica}}
    spec:
     source:
       snapshot:
        name: dv-volsnap
        namespace: vm-density-{{.Iteration}}
     storage:
       accessModes:
        - ReadWriteMany
       resources:
        requests:
          storage: {{.storage}}
       storageClassName: {{.storageclass}}
       volumeMode: {{.volumemode}}
